import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "./providers";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
          <Toaster duration={1500} richColors position="top-center" />
        </Provider>
      </body>
    </html>
  );
}
